spring:
  application:
    name: backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/impactamais}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  
  jpa:
    open-in-view: false
    hibernate:
      # DICA: Use 'update' no primeiro deploy para o Render criar as tabelas! 
      # Depois você pode voltar para 'validate'.
      ddl-auto: ${SPRING_JPA_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:contact.impactamais@gmail.com}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    virtual-host: ${SPRING_RABBITMQ_VHOST:/}

jwt:
  secret: ${JWT_SECRET:4a7d1ed414474e4033ac29ccb8653d9b18360d091f143714b2d3580424564c89}
  expiration: 86400000